### PR TITLE
Add Author class

### PR DESCRIPTION
**Pull request by enocol**
In this branch
The Author class has been created
An relationship of an association btween author and item class implimented (one to many)

### CODE REVIEW

**Review by newtonah0 — CHANGES_REQUESTED** [review]
hey @enocol you doing great work but you need to add accesses for author as  ( attr_reader attr_accessor )

**Comment by enocol** [comment]
Hi @newtonah0 Thanks for the review. I want to go ahead and implement the changes but i just wanted to understand more. The Author class according to the UML diagram is having as attributes(properties) an Id, First_name, Last_name, and an Items array lincluding method called add_item which should take as input  an instance of the Item class. Please could you explain further  about including an attribute reader or writer for author? Because Author is the class, I did not see any instance variable called author which need reading or setting it. Please help me understand properly so that i can make this change.

**Review by newtonah0 — CHANGES_REQUESTED** [review]
Sorry @enocol  now you missed the attr_accessor it will be looks like this 
  attr_accessor :first_name, :last_name, :items

**Review by newtonah0 — APPROVED** [review]
Great @enocol you merge it now.

**Pull request merged**
